name: "Backend build"
# .
on:
  push:
    paths:
      - "dapper/**"
      - "localtron/**"
      - ".github/workflows/backend-build-github.yaml"

jobs:
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22.4"

      - name: Install dependencies
        run: |
          cd localtron
          go mod tidy

      - name: Run tests
        run: |
          cd localtron

          docker rm -f mypostgres
          docker run --name mypostgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=mydatabase -p 5432:5432 -d postgres

          go test ./... -v

          # We rerun the tests with an SQL backend
          SINGULATRON_DB=postgres \
            SINGULATRON_DB_DEBUG=true \
            SINGULATRON_DB_SQL_CONNECTION_STRING="postgres://postgres:mysecretpassword@localhost:5432/mydatabase?sslmode=disable" \
            go test ./... -v
