name: "[GH] Localtron build"
# .
on:
  push:
    paths:
      - "dapper/**"
      - "localtron/**"
      - ".github/workflows/localtron-build-github.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22.4"

      - name: Install dependencies
        run: |
          cd localtron
          go mod tidy

      - name: Run tests
        run: |
          docker run --name mypostgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=mydatabase -p 5432:5432 -d postgres

          cd localtron
          go test ./... -v

          # We rerun the tests with an SQL backend
          export SINGULATRON_DB=postgres
          export SINGULATRON_DB_SQL_CONNECTION_STRING="postgres://postgres:mysecretpassword@localhost:5432/mydatabase?sslmode=disable"
          go test ./... -v
